name: 🚀 Build and release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - action.yml
      - package.json
      - package-lock.json

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      branch: v${{ steps.version.outputs.major }}
      tag: v${{ steps.pack.outputs.version }}
    steps:
      - name: ⚙️ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 🔃 Checkout
        uses: actions/checkout@v2

      - name: 🛠️ Install and build
        run: |
          npm ci
          npm i -g @vercel/ncc
          npm run build
      - name: 📦 Zip dist files
        id: pack
        uses: ./
        with:
          files: dist, action.yml

      - name: ⚙️ Unzip dist files
        run: |
          mkdir TODEPLOY
          unzip ${{ steps.pack.outputs.archive }} -d TODEPLOY
      - name: ⚙️ Parse version string
        id: version
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.pack.outputs.version }}

      - name: 📢 Publish dist files to dist branch
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: self
          BRANCH: v${{ steps.version.outputs.major }}
          FOLDER: TODEPLOY
          SKIP_EMPTY_COMMITS: true

  tag_version:
    needs: build_and_push
    runs-on: ubuntu-latest
    outputs:
      tagged: ${{ steps.check_tagged.outputs.tagged }}
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: 🔃 Checkout dist branch
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.build_and_push.outputs.branch }}
          fetch-depth: 0

      - name: ⚙️ Check tag exists
        id: check_tag
        uses: mukunku/tag-exists-action@v1.0.0
        with:
          tag: ${{ needs.build_and_push.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔖 Tag version
        id: tag
        if: ${{ steps.check_tag.outputs.exists == 'false' }}
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ needs.build_and_push.outputs.tag }}

      - name: ⚙️ Check created tag
        id: check_tagged
        run: |
          echo "::set-output name=tagged::${{ (steps.check_tag.outputs.exists == 'false') && (steps.tag.outputs.new_tag == steps.tag.outputs.tag) }}"
  create_release:
    needs: tag_version
    if: ${{ needs.tag_version.outputs.tagged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag_version.outputs.tag }}
          draft: true
