name: Build & Deploy Engine
on: [push, pull_request]
jobs:
#  cleanup:
#    runs-on: self-hosted
#    steps:
#    - name: Cleanup
#      run: rm -rf .* || true
  Installing:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  release:
    - name: Upload new release
      uses: FWGS/action-gh-release@v0.1.15
      with:
        name: Xash3D FWGS Continuous ${{ github.ref_name }} Build
        tag_name: ${{ github.ref_name == 'master' && 'continuous' || format('continuous-{0}', github.ref_name) }}
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ProBaseBuilder
        draft: false
